services:
  auth-db:
    image: 'postgres:16-alpine'

    container_name: auth-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - auth_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  chat-db:
    image: 'postgres:16-alpine'

    container_name: chat-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - chat_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  message-db:
    image: 'postgres:16-alpine'

    container_name: message-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - message_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  user-db:
    image: 'postgres:16-alpine'

    container_name: user-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5435:5432"

    volumes:
      - user_db_data:/var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3

  auth:
    container_name: auth

    image: $DOCKER_USERNAME/auth-service:dev

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      AUTH_DB_CONTAINER_NAME: ${AUTH_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      auth-db:
        condition: service_healthy

  chat:
    container_name: chat

    image: $DOCKER_USERNAME/chat-service:dev

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      CHAT_DB_CONTAINER_NAME: ${CHAT_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8081:8080"

    depends_on:
      chat-db:
        condition: service_healthy

  message:
    container_name: message

    image: $DOCKER_USERNAME/message-service:dev

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      MESSAGE_DB_CONTAINER_NAME: ${MESSAGE_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8082:8080"

    depends_on:
      message-db:
        condition: service_healthy

  user:
    container_name: user

    image: $DOCKER_USERNAME/user-service:dev

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      USER_DB_CONTAINER_NAME: ${USER_DB_CONTAINER_NAME}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8083:8080"

    depends_on:
      user-db:
        condition: service_healthy

  nginx:
    container_name: nginx

    image: nginx:1.25-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - auth
      - chat
      - message
      - user

  prometheus:
    container_name: prometheus
    image: prom/prometheus

    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring_net

    depends_on:
      - auth
      - chat
      - message
      - user

volumes:
  auth_db_data:
  chat_db_data:
  message_db_data:
  user_db_data:
  prometheus_data:

networks:
  monitoring_net:
    driver: bridge